In [1]:
import yfinance as yf
import pandas as pd
from pandas_datareader import data
import matplotlib.pyplot as plt
from tqdm import tqdm
import numpy as np
import plotly.graph_objects as go
from datetime import datetime, timedelta,date
from plotly.subplots import make_subplots
from sklearn.cluster import KMeans
from sklearn import metrics
from scipy.spatial.distance import cdist

yf.pdr_override()

In [2]:
def closest_support_resistance(close,lst):
    lst = np.asarray(lst)
    idx = (np.abs(lst-close)).argmin()
    return lst[idx]

def get_support_resist(price,last_5):
    K = 6
    kmeans = KMeans(n_clusters = K).fit(price)
    clusters = kmeans.predict(price)

    min_max_values = []

    for i in range(K):
        min_max_values.append([np.inf,-np.inf])

    for i in range(len(price)):
        cluster = clusters[i]

        # Min
        if price[i] < min_max_values[cluster][0]:
            min_max_values[cluster][0] = price[i]

        # Max    
        if price[i] > min_max_values[cluster][1]:
            min_max_values[cluster][1] = price[i]

    # List to contain
    support_resist = []

    # Sort cluster
    s = sorted(min_max_values, key = lambda x: x[0])

    # Get cluster average
    for i, (_min, _max) in enumerate(s):
        # min for first cluster
        if i == 0:
            support_resist.append(_min)

        # max for last cluster
        if i == len(min_max_values) - 1:
            support_resist.append(_max)

        # Append average
        else:
            support_resist.append(sum([_max, s[i+1][0]])/2)
            
    #30 day standard / upper band / lower band

    # Calculate and define moving average of 30 periods
    avg_30 = last_5['Close'].rolling(window=30).mean()

    # 30 days standard deviation
    std_30 = last_5['Close'].rolling(window=30).std()

    # Upper band
    upper = avg_30 + (std_30*2)

    # Lower band
    lower = avg_30 - (std_30*2)
    
    last_5['upper_band'] = upper
    last_5['lower_band'] = lower
    
    # Calculate and define moving average of 30 periods
    avg_30 = last_5['Close'].rolling(window=30, min_periods=1).mean()
    last_5['avg_30'] = avg_30
    
    
    price_action = last_5.copy()
    
    # Buy Sell Signal based on Bollinger Band Only
    price_action['signal'] = np.where(price_action['Close']>price_action['upper_band'],'Sell',
                                 np.where(price_action['Close']<price_action['lower_band'],'Buy','Hold'))
    

    buy = price_action.loc[price_action['signal']=='Buy']
    buy = buy[['Date','Close','signal']]

    sell = price_action.loc[price_action['signal']=='Sell']
    sell = sell[['Date','Close','signal']]
    
    fig = make_subplots(specs=[[{"secondary_y":True}]])        
    
    fig.add_trace(
        go.Candlestick(
            x = price_action['Date'],
            open = price_action['Open'],
            high = price_action['High'],
            low = price_action['Low'],
            close = price_action['Close'],
            name = 'stock',
            showlegend=True
        ),secondary_y=True
    )
    
    trace2 = {
        'x': price_action['Date'],
        'y': price_action['avg_30'],
        'type': 'scatter',
        'mode': 'lines',
        'line': {
            'width': 1,
            'color': 'orange'
                },
        'name': 'Moving Average of 30 periods'
    }
    
    fig.add_trace(trace2,secondary_y=True)
    

    
    trace3 = {
        'x': price_action['Date'],
        'y': price_action['upper_band'],
        'type': 'scatter',
        'mode': 'lines',
        'line': {'width': 1},
        'name': 'Bollinger Bands',
        'yaxis':'y',
        'marker':{'color':'indigo'},
        'hoverinfo':'none',
        'legendgroup':'Bollinger Bands'
    }

    trace4 = {
        'x': price_action['Date'],
        'y': price_action['lower_band'],
        'type': 'scatter',
        'mode': 'lines',
        'line': {'width': 1},
        'name': 'Bollinger Bands',
        'yaxis':'y',
        'marker':{'color':'indigo'},
        'hoverinfo':'none',
        'showlegend':False,
        'legendgroup':'Bollinger Bands'
    }
    
    fig.add_trace(trace3,secondary_y=True)
    fig.add_trace(trace4,secondary_y=True)
    
    fig.add_trace(go.Scatter(x=sell['Date'],y=sell['Close'],mode='markers',name='sell'),secondary_y=True)
    fig.add_trace(go.Scatter(x=buy['Date'],y=buy['Close'],mode='markers',name='buy'),secondary_y=True)
    
    for c_avg in support_resist:
        fig.add_hline(y = c_avg[0], line_width = 1, line_color = 'blue',secondary_y=True)
    
    fig.update_xaxes(
        rangeslider_visible=True,
        rangeselector=dict(
            buttons=list([
                dict(count=1, label="1m", step="month", stepmode="backward"),
                dict(count=3, label="3m", step="month", stepmode="backward"),
                dict(count=6, label="6m", step="month", stepmode="backward"),
                dict(count=1, label="YTD", step="year", stepmode="todate"),
                dict(count=1, label="1y", step="year", stepmode="backward"),
                dict(count=3, label="3y", step="year", stepmode="backward"),
                dict(count=5, label="5y", step="year", stepmode="backward"),
                dict(step="all")
            ])
        )
    )   
    
    fig.update_layout(hovermode='x',title='Bollinger Band')
    fig.update_yaxes(title='Volume',secondary_y=False,showgrid=False)
    fig.update_yaxes(title='Price',secondary_y=True,showgrid=True)
    fig.show()
    
    
    
    # Combine Bollinger Band & KMeans Support Resistance
    signal_lst = ['Hold']*len(price_action)
    for i in range(len(price_action)):
        if price_action['Close'][i] < price_action['lower_band'][i]:
            closest_lvl = closest_support_resistance(price_action['Close'][i],support_resist)[0]
            if (price_action['High'][i] >= closest_lvl)|(price_action['Close'][i] >= closest_lvl):
                signal_lst[i] = 'Buy'
            elif (price_action['High'][i] >= closest_lvl)|(price_action['Close'][i] <= closest_lvl):
                signal_lst[i] = 'Sell'
        if price_action['Close'][i] > price_action['upper_band'][i]:
            closest_lvl = closest_support_resistance(price_action['Close'][i],support_resist)[0]
            if (price_action['High'][i] >= closest_lvl)|(price_action['Close'][i] >= closest_lvl):
                continue
            elif (price_action['High'][i] >= closest_lvl)|(price_action['Close'][i] <= closest_lvl):
                signal_lst[i] = 'Sell'
        else:
            continue

    price_action['cross_signal'] = signal_lst

    buy = price_action.loc[price_action['cross_signal']=='Buy']
    buy = buy[['Date','Close','cross_signal']]

    sell = price_action.loc[price_action['cross_signal']=='Sell']
    sell = sell[['Date','Close','cross_signal']]
    
    fig = make_subplots(specs=[[{"secondary_y":True}]])        
    
    fig.add_trace(
        go.Candlestick(
            x = price_action['Date'],
            open = price_action['Open'],
            high = price_action['High'],
            low = price_action['Low'],
            close = price_action['Close'],
            name = 'stock',
            showlegend=True
        ),secondary_y=True
    )
    
    trace2 = {
        'x': price_action['Date'],
        'y': price_action['avg_30'],
        'type': 'scatter',
        'mode': 'lines',
        'line': {
            'width': 1,
            'color': 'orange'
                },
        'name': 'Moving Average of 30 periods'
    }
    
    fig.add_trace(trace2,secondary_y=True)
    

    
    trace3 = {
        'x': price_action['Date'],
        'y': price_action['upper_band'],
        'type': 'scatter',
        'mode': 'lines',
        'line': {'width': 1},
        'name': 'Bollinger Bands',
        'yaxis':'y',
        'marker':{'color':'indigo'},
        'hoverinfo':'none',
        'legendgroup':'Bollinger Bands'
    }

    trace4 = {
        'x': price_action['Date'],
        'y': price_action['lower_band'],
        'type': 'scatter',
        'mode': 'lines',
        'line': {'width': 1},
        'name': 'Bollinger Bands',
        'yaxis':'y',
        'marker':{'color':'indigo'},
        'hoverinfo':'none',
        'showlegend':False,
        'legendgroup':'Bollinger Bands'
    }
    
    fig.add_trace(trace3,secondary_y=True)
    fig.add_trace(trace4,secondary_y=True)
    
    fig.add_trace(go.Scatter(x=sell['Date'],y=sell['Close'],mode='markers',name='sell'),secondary_y=True)
    fig.add_trace(go.Scatter(x=buy['Date'],y=buy['Close'],mode='markers',name='buy'),secondary_y=True)
    
    for c_avg in support_resist:
        fig.add_hline(y = c_avg[0], line_width = 1, line_color = 'blue',secondary_y=True)
    
    fig.update_xaxes(
        rangeslider_visible=True,
        rangeselector=dict(
            buttons=list([
                dict(count=1, label="1m", step="month", stepmode="backward"),
                dict(count=3, label="3m", step="month", stepmode="backward"),
                dict(count=6, label="6m", step="month", stepmode="backward"),
                dict(count=1, label="YTD", step="year", stepmode="todate"),
                dict(count=1, label="1y", step="year", stepmode="backward"),
                dict(count=3, label="3y", step="year", stepmode="backward"),
                dict(count=5, label="5y", step="year", stepmode="backward"),
                dict(step="all")
            ])
        )
    )   
    
    fig.update_layout(hovermode='x',title='Bollinger Band + Support & Resistance')
    fig.update_yaxes(title='Volume',secondary_y=False,showgrid=False)
    fig.update_yaxes(title='Price',secondary_y=True,showgrid=True)
    fig.show()
    
    return support_resist,price_action

In [4]:
# Try to find the local maxima and local minima
# HK benchmark 3115.HK / 2800.HK
# US Benchmark SP500 -> IVV/ITOT/VOO/SPY, Nasdaq -> NASDX/QQQ, DOWS -> DIA, Russell 200 -> VTWO 
lst=['TSLA']
last5 = datetime.now() - timedelta(days=5*365+30)
last5_str = last5.strftime('%Y-%m-%d')
last_5 = data.DataReader(lst, start=last5_str).reset_index()

price = np.array(last_5['Adj Close']).reshape(-1,1)

support_resist,price_action = get_support_resist(price,last_5)

[*********************100%***********************]  1 of 1 completed


/Users/matthewong/opt/anaconda3/envs/finance/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



In [5]:
support_resist

[array([11.93133259]),
 array([77.60966492]),
 array([158.01000214]),
 array([211.16666412]),
 array([259.82832336]),
 array([320.81999207]),
 array([409.97000122])]

In [6]:
price_action.loc[price_action['cross_signal']=='Buy']

Date        Open        High         Low       Close   Adj Close  \
71   2018-09-28   18.017332   18.533333   17.370667   17.651333   17.651333   
76   2018-10-05   18.309999   18.325333   17.333332   17.463333   17.463333   
77   2018-10-08   17.634666   17.850668   16.600000   16.704000   16.704000   
128  2018-12-20   21.803333   22.019333   20.791332   21.025333   21.025333   
130  2018-12-24   20.900000   20.966667   19.680000   19.692667   19.692667   
177  2019-03-05   18.799999   18.933332   18.006666   18.436001   18.436001   
178  2019-03-06   18.431999   18.767332   18.292667   18.416000   18.416000   
179  2019-03-07   18.589333   18.980000   18.283333   18.439333   18.439333   
213  2019-04-25   17.000000   17.266666   16.404667   16.508667   16.508667   
214  2019-04-26   16.433332   16.445333   15.408667   15.676000   15.676000   
215  2019-04-29   15.724000   16.265333   15.478000   16.098000   16.098000   
216  2019-04-30   16.137333   16.280666   15.800000   15.912667   15.912667   
217  2019-05-01   15.923333   16.000000   15.433333   15.600667   15.600667   
229  2019-05-17   14.797333   14.816000   13.928000   14.068667   14.068667   
230  2019-05-20   13.520000   13.733333   13.016667   13.690667   13.690667   
231  2019-05-21   13.184000   13.826667   13.069333   13.672000   13.672000   
232  2019-05-22   13.273333   13.596000   12.785333   12.848667   12.848667   
233  2019-05-23   12.956000   13.298000   12.414667   13.032667   13.032667   
234  2019-05-24   13.322000   13.332000   12.583333   12.708667   12.708667   
435  2020-03-12   38.726002   39.633331   36.416668   37.369999   37.369999   
436  2020-03-13   39.666668   40.504665   33.466667   36.441334   36.441334   
437  2020-03-16   31.299999   32.991333   29.478001   29.671333   29.671333   
438  2020-03-17   29.334000   31.456667   26.400000   28.680000   28.680000   
439  2020-03-18   25.933332   26.990667   23.367332   24.081333   24.081333   
674  2021-02-23  220.710007  237.869995  206.333328  232.946671  232.946671   
676  2021-02-25  242.050003  245.736664  223.526672  227.406662  227.406662   
677  2021-02-26  233.333328  235.566666  219.836670  225.166672  225.166672   
680  2021-03-03  229.330002  233.566666  217.236664  217.733337  217.733337   
681  2021-03-04  218.600006  222.816666  200.000000  207.146667  207.146667   
909  2022-01-27  311.119995  311.796661  276.333344  276.366669  276.366669   
927  2022-02-23  276.809998  278.433319  253.520004  254.679993  254.679993   
979  2022-05-09  278.816681  281.876678  260.383331  262.369995  262.369995   
981  2022-05-11  265.000000  269.923340  242.399994  244.666672  244.666672   
1084 2022-10-07  233.940002  234.570007  222.020004  223.070007  223.070007   
1085 2022-10-10  223.929993  226.990005  218.360001  222.960007  222.960007   
1086 2022-10-11  220.949997  225.750000  215.000000  216.500000  216.500000   
1107 2022-11-09  190.779999  195.889999  177.119995  177.589996  177.589996   
1115 2022-11-21  175.850006  176.770004  167.539993  167.869995  167.869995   
1131 2022-12-14  159.250000  161.619995  155.309998  156.800003  156.800003   
1133 2022-12-16  159.639999  160.990005  150.039993  150.229996  150.229996   
1139 2022-12-27  117.500000  119.669998  108.760002  109.099998  109.099998   
1140 2022-12-28  110.349998  116.269997  108.239998  112.709999  112.709999   
1217 2023-04-20  166.169998  169.699997  160.559998  162.990005  162.990005   
1218 2023-04-21  164.800003  166.000000  161.320007  165.080002  165.080002   
1219 2023-04-24  164.649994  165.649994  158.610001  162.550003  162.550003   
1220 2023-04-25  159.820007  163.470001  158.750000  160.669998  160.669998   
1221 2023-04-26  160.289993  160.669998  153.139999  153.750000  153.750000   

         Volume  upper_band  lower_band      avg_30 signal cross_signal  
71    504745500   21.994020   17.802246   19.898133    Buy          Buy  
76    269167500   21.642508   17.588070   19.615289    Buy          Bu

In [7]:
avg_price = 0
position = 0
profit_loss = 0
for i in range(len(price_action)):
    if position == 0:
        if (price_action['cross_signal'][i] == 'Buy'):
            print(price_action['Date'][i], 'Buy')
            avg_price = (avg_price*position + price_action['Close'][i]*1000)/ (position+1000)
            position += 1000
            print('Average Cost:',avg_price,'Position',position)
        else:
            continue
    elif position > 0:
        if (price_action['cross_signal'][i] == 'Buy'):
            print(price_action['Date'][i], 'Buy')
            avg_price = (avg_price*position + price_action['Close'][i]*1000)/ (position+1000)
            position += 1000
            print('Average Cost:',avg_price,'Position',position)
        elif (price_action['cross_signal'][i] == 'Sell'):
            if avg_price > price_action['Close'][i]:
                continue
            else:
                print(price_action['Date'][i],'Sell')
                profit_loss += (price_action['Close'][i]- avg_price)*1000 
                position += -1000
                print('Average Cost:',avg_price,'Position',position,'P/L:',profit_loss)
        else:
            continue
    else:
        continue

2018-09-28 00:00:00 Buy
Average Cost: 17.65133285522461 Position 1000
2018-10-05 00:00:00 Buy
Average Cost: 17.55733299255371 Position 2000
2018-10-08 00:00:00 Buy
Average Cost: 17.27288881937663 Position 3000
2018-12-20 00:00:00 Buy
Average Cost: 18.210999965667725 Position 4000
2018-12-24 00:00:00 Buy
Average Cost: 18.50733337402344 Position 5000
2019-03-05 00:00:00 Buy
Average Cost: 18.495444615681965 Position 6000
2019-03-06 00:00:00 Buy
Average Cost: 18.484095437186106 Position 7000
2019-03-07 00:00:00 Buy
Average Cost: 18.47850012779236 Position 8000
2019-04-25 00:00:00 Buy
Average Cost: 18.25962977939182 Position 9000
2019-04-26 00:00:00 Buy
Average Cost: 18.001266765594483 Position 10000
2019-04-29 00:00:00 Buy
Average Cost: 17.82824247533625 Position 11000
2019-04-30 00:00:00 Buy
Average Cost: 17.66861120859782 Position 12000
2019-05-01 00:00:00 Buy
Average Cost: 17.509538577153133 Position 13000
2019-05-17 00:00:00 Buy
Average Cost: 17.263762065342494 Position 14000
2019-05-2

In [8]:
avg_price

166.32666755445075

In [9]:
position

4000

In [10]:
profit_loss

3678465.3263381044

In [11]:
unrealized = (price_action['Close'].iloc[-1] - avg_price)*position
print('Unrealized:',unrealized)

Unrealized: 496213.349313447


In [12]:
avg_price = 0
position = 0
profit_loss = 0
for i in range(len(price_action)):
    if position == 0:
        if (price_action['cross_signal'][i] == 'Buy'):
            print(price_action['Date'][i], 'Buy')
            avg_price = (avg_price*position + price_action['Close'][i]*1000)/ (position+1000)
            position += 1000
            print('Average Cost:',avg_price,'Position',position)
        else:
            continue
    elif position > 0:
        if (price_action['cross_signal'][i] == 'Buy'):
            print(price_action['Date'][i], 'Buy')
            avg_price = (avg_price*position + price_action['Close'][i]*1000)/ (position+1000)
            position += 1000
            print('Average Cost:',avg_price,'Position',position)
        elif (price_action['cross_signal'][i] == 'Sell'):
            print(price_action['Date'][i],'Sell')
            profit_loss += (price_action['Close'][i]- avg_price)*1000 
            position += -1000
            print('Average Cost:',avg_price,'Position',position,'P/L:',profit_loss)
        else:
            continue
    else:
        continue

2018-09-28 00:00:00 Buy
Average Cost: 17.65133285522461 Position 1000
2018-10-05 00:00:00 Buy
Average Cost: 17.55733299255371 Position 2000
2018-10-08 00:00:00 Buy
Average Cost: 17.27288881937663 Position 3000
2018-12-20 00:00:00 Buy
Average Cost: 18.210999965667725 Position 4000
2018-12-24 00:00:00 Buy
Average Cost: 18.50733337402344 Position 5000
2019-03-05 00:00:00 Buy
Average Cost: 18.495444615681965 Position 6000
2019-03-06 00:00:00 Buy
Average Cost: 18.484095437186106 Position 7000
2019-03-07 00:00:00 Buy
Average Cost: 18.47850012779236 Position 8000
2019-04-25 00:00:00 Buy
Average Cost: 18.25962977939182 Position 9000
2019-04-26 00:00:00 Buy
Average Cost: 18.001266765594483 Position 10000
2019-04-29 00:00:00 Buy
Average Cost: 17.82824247533625 Position 11000
2019-04-30 00:00:00 Buy
Average Cost: 17.66861120859782 Position 12000
2019-05-01 00:00:00 Buy
Average Cost: 17.509538577153133 Position 13000
2019-05-17 00:00:00 Buy
Average Cost: 17.263762065342494 Position 14000
2019-05-2

In [13]:
profit_loss

3364665.3394699106

In [14]:
unrealized = (price_action['Close'].iloc[-1] - avg_price)*position
unrealized

0.0